import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className=" bg-white overflow-y-auto bg-opacity-80">
					<div >
						<Navbar />
					</div>
					<div className=" mt-16" >{children}</div>
				</main>
			</body>
		</html>
	);
}
